sonar.projectKey=eltu_idx-lib
sonar.organization=eltu
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/bin/**,**/mocks/**,docs/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
